import { DeleteObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '../../prisma/prisma.service';
import { runWithoutTenant } from '../../prisma/tenant-context';
import { captureException } from '../../observability/sentry';

/**
 * After this many failed attempts a job stops being retried and is parked as
 * 'dead'. Without a cap a permanently-poisoned job (revoked bucket policy,
 * malformed legacy key) retries hourly forever, and 100 of them at the head of
 * the queue starve every newer erasure behind them.
 */
const MAX_ATTEMPTS = 10;

/**
 * Every key in the outbox is server-generated by s3-image.service.ts or
 * s3-document.service.ts as `<prefix>/<venueId>/<32 hex>`. Nothing accepts a
 * key from a client today, and this guard exists so that stays true: one
 * future bug writing a client-influenced string into objectKeys would
 * otherwise become bucket-wide deletion, since the IAM credential is shared
 * with the upload path.
 */
const OBJECT_KEY_PATTERN = /^(chat|documents)\/[A-Za-z0-9_-]+\/[a-f0-9]{32}$/;

@Injectable()
export class MediaCleanupService {
  private readonly logger = new Logger(MediaCleanupService.name);
  private readonly s3: S3Client;
  private readonly bucket: string;

  constructor(private readonly prisma: PrismaService, config: ConfigService) {
    this.s3 = new S3Client({
      region: config.get<string>('AWS_REGION', 'us-east-1'),
      credentials: {
        accessKeyId: config.getOrThrow<string>('AWS_ACCESS_KEY_ID'),
        secretAccessKey: config.getOrThrow<string>('AWS_SECRET_ACCESS_KEY'),
      },
    });
    this.bucket = config.getOrThrow<string>('AWS_S3_BUCKET');
  }

  async processJob(id: string): Promise<boolean> {
    // The whole body is guarded: previously only the S3 loop was, so a Prisma
    // error on the claim or the status write escaped to the caller — 500ing a
    // delete that had already committed, and aborting the rest of a cron batch.
    try {
      return await runWithoutTenant(async () => {
        const claimed = await this.prisma.objectDeletionJob.updateMany({
          where: { id, status: { in: ['pending', 'failed'] }, attempts: { lt: MAX_ATTEMPTS } },
          data: { status: 'processing', attempts: { increment: 1 }, lastError: null },
        });
        if (claimed.count !== 1) return false;
        const job = await this.prisma.objectDeletionJob.findUnique({ where: { id } });
        if (!job) return false;

        const keys = Array.from(new Set(job.objectKeys));
        const unsafe = keys.filter((key) => !OBJECT_KEY_PATTERN.test(key));
        if (unsafe.length > 0) {
          // Never a transient condition — park it immediately rather than
          // retrying, and make it loud: it means something wrote a key we did
          // not generate.
          const message = `Refusing to delete ${unsafe.length} key(s) not matching the expected object-key format.`;
          await this.prisma.objectDeletionJob.update({
            where: { id },
            data: { status: 'dead', lastError: message.slice(0, 1000) },
          });
          this.logger.error(`Object deletion job ${id} parked: ${message}`);
          captureException(new Error(message), { jobId: id, unsafeKeyCount: unsafe.length });
          return false;
        }

        try {
          for (const key of keys) {
            await this.s3.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
          }
          await this.prisma.objectDeletionJob.update({
            where: { id },
            data: { status: 'completed', completedAt: new Date(), lastError: null },
          });
          return true;
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          const exhausted = job.attempts + 1 >= MAX_ATTEMPTS;
          await this.prisma.objectDeletionJob.update({
            where: { id },
            data: { status: exhausted ? 'dead' : 'failed', lastError: message.slice(0, 1000) },
          });
          this.logger.error(
            `Object deletion job ${id} ${exhausted ? 'exhausted retries' : 'failed'}: ${message}`,
          );
          // Background work never reaches AllExceptionsFilter, so without this
          // an unfulfilled erasure request is invisible outside the logs.
          captureException(error, { jobId: id, attempts: job.attempts + 1, exhausted });
          return false;
        }
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.error(`Object deletion job ${id} could not be processed: ${message}`);
      captureException(error, { jobId: id, phase: 'claim' });
      return false;
    }
  }

  @Cron(CronExpression.EVERY_HOUR)
  async retryPendingJobs(): Promise<void> {
    try {
      const abandonedCutoff = new Date(Date.now() - 15 * 60 * 1000);
      await runWithoutTenant(() => this.prisma.objectDeletionJob.updateMany({
        where: { status: 'processing', updatedAt: { lt: abandonedCutoff } },
        data: { status: 'failed', lastError: 'Worker stopped before completing object deletion.' },
      }));
      // 'dead' jobs are excluded by the attempts cap so a poisoned job cannot
      // occupy a slot in every batch forever.
      const jobs = await runWithoutTenant(() => this.prisma.objectDeletionJob.findMany({
        where: { status: { in: ['pending', 'failed'] }, attempts: { lt: MAX_ATTEMPTS } },
        orderBy: { createdAt: 'asc' },
        take: 100,
        select: { id: true },
      }));
      // processJob swallows its own errors, but guard the loop anyway so one
      // unexpected throw cannot skip every remaining job in the batch.
      for (const job of jobs) {
        try {
          await this.processJob(job.id);
        } catch (error) {
          this.logger.error(`Object deletion job ${job.id} threw during batch retry.`);
          captureException(error, { jobId: job.id, phase: 'batch' });
        }
      }

      const deadCount = await runWithoutTenant(() => this.prisma.objectDeletionJob.count({
        where: { status: 'dead' },
      }));
      if (deadCount > 0) {
        // Surfaced every hour on purpose: a dead job is an erasure request that
        // will never complete without a human looking at it.
        this.logger.error(`${deadCount} object deletion job(s) are parked as dead and need review.`);
        captureException(new Error(`${deadCount} object deletion job(s) parked as dead`), { deadCount });
      }
    } catch (error) {
      // Cron callbacks have no request exception filter. Capture a database
      // outage or an unexpected query failure instead of leaving it only in
      // the scheduler's process log.
      this.logger.error('Object deletion retry pass failed.');
      captureException(error, { phase: 'retry-batch' });
    } finally {
      // Retention runs even if the retry pass above threw, so completed rows
      // cannot accumulate behind a failure.
      const retentionCutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
      await runWithoutTenant(() => this.prisma.objectDeletionJob.deleteMany({
        where: { status: 'completed', completedAt: { lt: retentionCutoff } },
      })).catch((error: unknown) => {
        this.logger.error('Object deletion retention sweep failed.');
        captureException(error, { phase: 'retention' });
      });
    }
  }
}
