import { useEffect, useRef, useState, type FormEvent } from 'react';
import { motion, MotionConfig } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Play, Check, Layers, LayoutGrid, Wine, Radio, Clock3, ChevronRight, X, Menu, ScanLine, ShieldCheck, Zap, Smartphone, Activity, Bell, CircleCheck, Command } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
const cn = (...values: Parameters<typeof clsx>) => twMerge(clsx(...values));
const iosUrl = 'https://apps.apple.com/app/id6772533789';
const reveal = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: .65 } };
function Brand() { return <a className="brand" href="#" aria-label="Venue Wrangler home"><span className="brand-mark"><Command size={21}/></span><span>VENUE<span className="brand-light">WRANGLER</span></span><i className="live-dot"/></a>; }
function Navbar() {
    const [open, setOpen] = useState(false);
    return <header className="navbar"><div className="nav-inner"><Brand /><nav aria-label="Main navigation" className={cn('nav-links', open && 'is-open')}><a href="#features" onClick={() => setOpen(false)}>Features</a><a href="#standard" onClick={() => setOpen(false)}>The Standard</a><a href="#integrations" onClick={() => setOpen(false)}>Integrations</a><a href="#pricing" onClick={() => setOpen(false)}>Pricing</a></nav><div className="nav-actions"><a className="signin" href="app/sign-in">Operator Sign In <ArrowUpRight size={14}/></a><a className="button small" href="#launch">Launch Workspace <ArrowUpRight size={15}/></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></div></header>;
}
function FloorMatrix() { return <div className="floor-matrix"><div className="floor-zone">MAIN DINING <span>12 / 16 SEATED</span></div><div className="table-grid">{Array.from({ length: 12 }, (_, i) => <div key={i} className={cn('floor-table', i === 7 ? 'vip' : i % 4 === 0 ? 'available' : 'seated')}><span>{String(i + 1).padStart(2, '0')}</span><small>{i === 7 ? 'VIP' : i % 4 === 0 ? 'OPEN' : `${24 + i * 3}m`}</small></div>)}</div><div className="floor-legend"><span><i />Seated</span><span><i />Available</span><span><i />VIP arrival</span></div></div>; }
function CommandDashboard() { return <motion.div {...reveal} transition={{ delay: .15, duration: .8 }} className="dashboard-wrap"><div className="dashboard-glow"/><div className="dashboard"><div className="window-bar"><div className="window-dots"><i /><i /><i /></div><span><ShieldCheck size={11}/> WORKSPACE / THE MIDNIGHT COLLECTIVE</span><span className="demo-tag">DEMO WORKSPACE</span></div><div className="dashboard-body"><aside className="dashboard-sidebar"><Command size={21}/><LayoutGrid className="active" size={19}/><Layers size={19}/><Wine size={19}/><Activity size={19}/><span className="avatar">MC</span></aside><div className="dashboard-content"><div className="dashboard-heading"><div><span className="micro">FRIDAY, OCTOBER 24 · EVENING SERVICE</span><h3>Tonight, in command.</h3></div><span className="status-pill"><i className="live-dot"/> Systems operational</span></div><div className="dashboard-stats"><div><span>ON THE FLOOR</span><strong>142<small> / 180 guests</small></strong></div><div><span>TEAM ON SHIFT</span><strong>24<small className="emerald"> All positions covered</small></strong></div><div><span>EVENT READINESS</span><strong>94<small>% <span className="emerald">↗ Ready for doors</span></small></strong></div></div><div className="hud-grid"><section className="hud floor-hud"><div className="hud-title"><LayoutGrid size={14}/><h4>Live floor matrix</h4><span>ZONE 01</span></div><FloorMatrix /><div className="floor-notice"><span className="amber-dot"/><span><strong>Table 12 · VIP arrival</strong><small>Champagne service in progress</small></span><ChevronRight size={14}/></div></section><div className="hud-stack"><section className="hud"><div className="hud-title"><Layers size={14}/><h4>Buyout readiness</h4><span className="emerald">94%</span></div><p className="hud-sub">The Founder's Dinner <span>19:00</span></p><div className="progress-track"><span /></div><div className="checks"><span><CircleCheck /> BEO confirmed</span><span><CircleCheck /> Kitchen briefed</span><span className="amber"><Clock3 /> Final room check</span></div></section><section className="hud bar-hud"><div className="hud-title"><Wine size={14}/><h4>Live bar par feed</h4><Radio size={13} className="emerald"/></div><div className="bottle-row"><span className="bottle">▥</span><div><strong>Don Julio 1942</strong><small>Tequila · Back bar</small></div><span className="stock">8<small>bottles</small></span></div><div className="par-optimal"><i className="live-dot"/> Par optimal <span>Last counted 18:42</span></div></section></div></div><div className="dashboard-bottom"><span><Radio size={10}/> One operation. One source of truth.</span><span>ILLUSTRATIVE DATA</span></div></div></div></div><div className="floating-alert"><span className="alert-icon"><Check size={17}/></span><div><strong>From confirmed to coordinated.</strong><small>Your next move is already in motion.</small></div></div></motion.div>; }
function HeroSection({ onTour }: {
    onTour: () => void;
}) { return <section className="hero"><div className="hero-grid"/><div className="container"><motion.div {...reveal} className="hero-copy"><span className="eyebrow"><i className="live-dot"/> THE OPERATIONAL OPERATING SYSTEM</span><h1>Run Friday Night<br /><span>Like It’s Scripted.</span></h1><p>Close the gap between the floor, the bar, and the back office.<br className="desktop-break"/> One command center for the people who run the room.</p><div className="hero-actions"><a className="button" href="#launch">Launch Your Workspace <ArrowUpRight size={18}/></a><button className="button glass" onClick={onTour}><Play size={15} fill="currentColor"/> Watch the Command Tour</button></div><div className="hero-note"><span><Check size={12}/> Built for real service</span><span><Check size={12}/> Web + iOS, in sync</span><span><Check size={12}/> From one room to many</span></div></motion.div><CommandDashboard /><div className="hero-caption"><span>THE FLOOR. THE BAR. THE BIG PICTURE.</span><span>FINALLY, ON THE SAME PAGE. <ArrowRight size={12}/></span></div></div></section>; }
function IntegrationsStrip() { return <section id="integrations" className="integrations"><div className="container"><div className="section-kicker">YOUR OPERATION DOESN’T START FROM ZERO. NEITHER DO WE.</div><div className="provider-row" aria-label="Integration ecosystem"><span className="toast">toast</span><span className="square"><span>▣</span> Square</span><span>✣ clover</span><span className="resy">Resy</span><span className="opentable">◉ OpenTable</span><span className="seven">SEVENROOMS</span></div><p>Explore our POS and reservation ecosystem. Connection availability and setup vary by provider. <a href="support/">Check your setup <ArrowUpRight size={12}/></a></p></div></section>; }
function ComparisonMatrix() { return <section id="standard" className="section container"><div className="section-top"><span className="eyebrow plain">01 / THE NEW STANDARD</span><h2>Service is complex.<br /><span>Your systems shouldn’t be.</span></h2><p>When every department sees a different picture,<br />you spend the night connecting the dots.</p></div><div className="comparison"><div className="comparison-card fragmented"><span className="micro">THE WAY IT’S ALWAYS BEEN</span><h3>The fragmented floor.</h3>{['Paper BEOs. Last-minute changes. Missed handoffs.', 'Five disconnected systems and a dozen open tabs.', 'Finding out you’re out of a key SKU at 11:30 PM.'].map(x => <p key={x}><X size={16}/>{x}</p>)}<div className="fragment-tags"><span>POS</span><span>Spreadsheets</span><span>Group chats</span><span>Clipboards</span></div></div><div className="comparison-card unified"><span className="micro emerald"><i className="live-dot"/> THE VENUE WRANGLER STANDARD</span><h3>The unified engine.</h3>{['Confirmed BEOs become an actionable event plan.', 'Floor plans, your team, and service in one workspace.', 'Camera and barcode counts before doors open.'].map(x => <p key={x}><Check size={16}/>{x}</p>)}<div className="connected-line"><Command size={20}/><span>ONE OPERATION. FULL VISIBILITY.</span><ArrowUpRight size={16}/></div></div></div></section>; }
const features = [
    { icon: Layers, label: 'Event-day command', eyebrow: 'FROM THE BEO TO THE LAST CALL', title: 'Every detail.\nAlready accounted for.', body: 'Turn a confirmed event into a shared execution plan. Keep milestones, vendor arrivals, and kitchen handoffs visible to everyone running the show.', bullets: ['Shared event milestones and ownership', 'Vendor status and arrival tracking', 'One briefing for every department'] },
    { icon: LayoutGrid, label: 'Spatial floor & velocity', eyebrow: 'READ THE ROOM. IN REAL TIME.', title: 'Know your floor.\nOwn the flow.', body: 'See the room by zone, keep table status current, and coordinate your next seating from the floor or the back office.', bullets: ['Main dining, VIP, and patio layouts', 'Live seating and table turn context', 'A shared view for hosts and managers'] },
    { icon: Wine, label: 'High-velocity inventory', eyebrow: 'COUNT IT. KNOW IT. KEEP SERVICE MOVING.', title: 'Stay ahead\nof the next pour.', body: 'Bring camera-assisted counts, barcode scanning, and invoice capture into one inventory workflow. Review estimates and reconcile stock before service starts.', bullets: ['Camera-assisted bottle counts', 'Barcode and invoice capture', 'Stock movement and par visibility'] }
];
function FeatureVisual({ index }: {
    index: number;
}) { if (index === 1)
    return <div className="feature-demo"><div className="demo-heading"><LayoutGrid size={16}/> FLOOR OVERVIEW <span>3 ZONES</span></div><div className="zone-tabs">Main dining <span>VIP mezzanine</span><span>Patio</span></div><FloorMatrix /></div>; if (index === 2)
    return <div className="feature-demo"><div className="demo-heading"><ScanLine size={16}/> INVENTORY COUNT <span>PRE-SERVICE</span></div><div className="scanner"><ScanLine size={90} strokeWidth={.7}/><span>BARCODE CAPTURE</span></div><div className="timeline-row"><span className="task-check"><Check size={12}/></span><div><strong>Back bar count reviewed</strong><small>8 bottles · Don Julio 1942</small></div><span className="emerald">Saved</span></div><div className="timeline-row"><Wine size={17}/><div><strong>Distributor invoice</strong><small>Review quantities before accepting</small></div><span className="amber">Review</span></div></div>; return <div className="feature-demo"><div className="demo-heading"><Layers size={16}/> THE FOUNDER’S DINNER <span>TONIGHT / 19:00</span></div><div className="event-summary"><div><small>EVENT EXECUTION</small><h4>All hands. One plan.</h4></div><span className="ring">94<small>%</small></span></div>{[['17:00', 'BEO confirmed', 'Event manager', 'done'], ['17:30', 'Vendor load-in complete', 'Operations', 'done'], ['18:00', 'Kitchen briefing', 'Executive chef', 'done'], ['18:45', 'Final room check', 'Floor manager', 'pending']].map(([time, title, owner, status]) => <div className="timeline-row" key={time}><span className="timeline-time">{time}</span><span className={cn('task-check', status === 'pending' && 'pending')}>{status === 'done' ? <Check size={12}/> : <Clock3 size={12}/>}</span><div><strong>{title}</strong><small>{owner}</small></div><span className={status === 'done' ? 'emerald' : 'amber'}>{status === 'done' ? 'Complete' : 'Up next'}</span></div>)}<div className="demo-foot"><Bell size={12}/> The right people. The right information. At the right time.</div></div>; }
function FeatureTabs() { const [active, setActive] = useState(0); const selected = features[active]; return <section id="features" className="section feature-section"><div className="container"><div className="section-top"><span className="eyebrow plain">02 / YOUR OPERATION, CONNECTED</span><h2>Three moving parts.<br /><span>One steady hand.</span></h2></div><div className="feature-tabs" role="tablist" aria-label="Product features">{features.map((f, i) => <button id={`feature-tab-${i}`} key={f.label} role="tab" aria-selected={active === i} aria-controls="feature-panel" tabIndex={active === i ? 0 : -1} className={cn(active === i && 'selected')} onClick={() => setActive(i)} onKeyDown={e => { let next = active; if (e.key === 'ArrowRight')
    next = (active + 1) % 3;
else if (e.key === 'ArrowLeft')
    next = (active + 2) % 3;
else if (e.key === 'Home')
    next = 0;
else if (e.key === 'End')
    next = 2;
else
    return; e.preventDefault(); setActive(next); document.getElementById(`feature-tab-${next}`)?.focus(); }}><f.icon size={17}/>{f.label}<ArrowUpRight size={14}/></button>)}</div><div id="feature-panel" role="tabpanel" aria-labelledby={`feature-tab-${active}`} className="feature-panel"><motion.div key={active} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="feature-copy"><span className="micro emerald">{selected.eyebrow}</span><h3>{selected.title}</h3><p>{selected.body}</p><ul>{selected.bullets.map(b => <li key={b}><Check size={15}/>{b}</li>)}</ul><a href="#launch">Put it to work <ArrowRight size={15}/></a></motion.div><div><FeatureVisual index={active}/><span className="example-label">PRODUCT WALKTHROUGH · ILLUSTRATIVE DATA</span></div></div></div></section>; }
function Credo() { return <section className="credo container"><span className="quote-mark">“</span><blockquote>Most hospitality software was designed for accountants, not the managers standing on the floor during a <span>9:00 PM rush.</span></blockquote><p>Venue Wrangler is built for the operators who have to make it all happen.</p><div className="credo-signature"><span className="brand-mark"><Command size={16}/></span><span>THE OPERATOR’S CREDO<small>THE PRINCIPLE BEHIND VENUE WRANGLER</small></span></div></section>; }
function ConversionFooter() { function start(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); try {
    sessionStorage.setItem('vw-workspace-draft', JSON.stringify({ venue: String(data.get('venue') || '').trim(), email: String(data.get('email') || '').trim() }));
}
catch { } window.location.assign('start/'); } return <><section id="pricing" className="pricing container"><div><span className="micro emerald">A WORKSPACE THAT FITS YOUR OPERATION</span><h3>One venue or a whole portfolio.</h3><p>Explore the right plan for your team. Pricing and subscription terms are shown during setup.</p></div><a className="button glass" href="support/">Talk through your setup <ArrowUpRight size={16}/></a></section><section id="launch" className="conversion container"><div className="conversion-head"><span className="eyebrow plain">YOUR NEXT SERVICE STARTS HERE</span><h2>Doors open soon.<br /><span>Be ready for anything.</span></h2><p>Bring your team, your floor, and your next big night together.</p></div><div className="conversion-grid"><form onSubmit={start}><span className="micro"><LayoutGrid size={14}/> LAUNCH YOUR WEB WORKSPACE</span><div className="start-inputs"><label>Venue name<input name="venue" autoComplete="organization" placeholder="The name above your door" required maxLength={120}/></label><label>Work email<input type="email" name="email" autoComplete="email" placeholder="you@yourvenue.com" required/></label></div><button className="button" type="submit">Let’s get you in command <ArrowRight size={16}/></button><small>Next: create your account and verify your email.</small></form><div className="mobile-bridge"><a className="qr" href={iosUrl} aria-label="Download Venue Wrangler on the App Store"><QRCodeSVG value={iosUrl} size={108} marginSize={2} level="M"/></a><div><span className="micro"><Smartphone size={13}/> COMMAND, IN YOUR POCKET</span><h3>Your floor moves.<br />Move with it.</h3><p>Scan to find Venue Wrangler on iOS.</p><a href={iosUrl}>View on the App Store <ArrowUpRight size={13}/></a></div></div></div><div className="trust-row"><span><ShieldCheck size={14}/> Encrypted in transit</span><span><Zap size={14}/> Roster import tools</span><span><Smartphone size={14}/> One account, web + iOS</span></div></section><footer className="footer container"><Brand /><span>© {new Date().getFullYear()} Loungeability LLC.</span><nav aria-label="Footer"><a href="privacy/">Privacy</a><a href="terms/">Terms</a><a href="support/">Contact</a></nav><span className="footer-end"><i className="live-dot"/> BUILT FOR THE SHIFT.</span></footer></>; }
function Tour({ onClose }: {
    onClose: () => void;
}) { const dialog = useRef<HTMLDialogElement>(null); useEffect(() => { const el = dialog.current; const previous = document.activeElement as HTMLElement; el?.showModal(); return () => { el?.close(); previous?.focus(); }; }, []); return <dialog ref={dialog} className="tour-dialog" onCancel={onClose} onClick={e => { if (e.target === dialog.current)
    onClose(); }}><div className="tour-inner"><button className="close-tour" onClick={onClose} aria-label="Close command tour"><X /></button><span className="micro emerald">THE VENUE WRANGLER COMMAND TOUR</span><h2>See the bigger picture.</h2><video src="assets/venue-wrangler-ad.mp4" controls autoPlay playsInline preload="metadata"/><p>See how one workspace brings the moving parts of service together.</p><a className="button" href="#launch" onClick={onClose}>Launch your workspace <ArrowRight size={16}/></a></div></dialog>; }
export function App() { const [tour, setTour] = useState(false); return <MotionConfig reducedMotion="user"><a className="skip-link" href="#main">Skip to content</a><Navbar /><main id="main"><HeroSection onTour={() => setTour(true)}/><IntegrationsStrip /><ComparisonMatrix /><FeatureTabs /><Credo /><ConversionFooter /></main>{tour && <Tour onClose={() => setTour(false)}/>}</MotionConfig>; }
