import { cpSync, existsSync, lstatSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { shouldCopySiteSource } from './site-build-files.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const marketing = spawnSync(process.execPath, [join(root, 'node_modules/vite/bin/vite.js'), 'build'], {
  cwd: join(root, 'packages/marketing'), stdio: 'inherit',
});
if (marketing.error) throw marketing.error;
if (marketing.status !== 0) process.exit(marketing.status ?? 1);
const output = join(root, 'dist-site');
const marker = join(output, '.venue-site-build');
if (existsSync(output)) {
  if (lstatSync(output).isSymbolicLink() || !existsSync(marker)) {
    throw new Error('Refusing to replace dist-site: it is not a generated site build.');
  }
  rmSync(output, { recursive: true });
}
mkdirSync(output);
writeFileSync(marker, 'Generated by scripts/build-site.mjs\n');

cpSync(join(root, 'site'), output, { recursive: true, filter: (source) => shouldCopySiteSource(source, root) });
console.log('Built marketing site in dist-site.');
