import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
import { shouldCopySiteSource } from './site-build-files.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const marketing = spawnSync(process.execPath, [join(root, 'node_modules/vite/bin/vite.js'), 'build'], {
  cwd: join(root, 'packages/marketing'), stdio: 'inherit',
  env: { ...process.env, EXPO_NO_DOTENV: '1' },
});
if (marketing.error) throw marketing.error;
if (marketing.status !== 0) process.exit(marketing.status ?? 1);
const output = join(root, 'dist-site');
const marker = join(output, '.venue-site-build');
if (existsSync(output)) {
  if (lstatSync(output).isSymbolicLink() || !existsSync(marker)) {
    throw new Error('Refusing to replace dist-site: it is not a generated site build.');
  }
  rmSync(output, { recursive: true });
}
mkdirSync(output);
writeFileSync(marker, 'Generated by scripts/build-site.mjs\n');

// Do not ship the old checked-in Expo bundle: always compile current source.
cpSync(join(root, 'site'), output, { recursive: true, filter: (source) => shouldCopySiteSource(source, root) });
const require = createRequire(import.meta.url);
const result = spawnSync(process.execPath, [require.resolve('expo/bin/cli'), 'export', '--platform', 'web', '--output-dir', join(output, 'app')], {
  cwd: root,
  stdio: 'inherit',
  env: { ...process.env, EXPO_NO_DOTENV: '1', EXPO_WEB_BASE_PATH: '/app', CI: '1' },
});
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
const html = readFileSync(join(output, 'app', 'index.html'), 'utf8');
if (!html.includes('/app/_expo/')) throw new Error('Hosted bundle is missing its /app asset prefix.');
console.log('Built marketing site and current Expo client in dist-site.');
