import { cpSync, existsSync, lstatSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { shouldCopySiteSource } from './site-build-files.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const marketing = spawnSync(process.execPath, [join(root, 'node_modules/vite/bin/vite.js'), 'build'], {
  cwd: join(root, 'packages/marketing'), stdio: 'inherit',
});
if (marketing.error) throw marketing.error;
if (marketing.status !== 0) process.exit(marketing.status ?? 1);
const output = join(root, 'dist-site');
const marker = join(output, '.venue-site-build');
if (existsSync(output)) {
  if (lstatSync(output).isSymbolicLink() || !existsSync(marker)) {
    throw new Error('Refusing to replace dist-site: it is not a generated site build.');
  }
  rmSync(output, { recursive: true });
}
mkdirSync(output);
writeFileSync(marker, 'Generated by scripts/build-site.mjs\n');

cpSync(join(root, 'site'), output, { recursive: true, filter: (source) => shouldCopySiteSource(source, root) });

// The Flutter web app is served at /app/ — it's what "Operator Sign In" and "Launch Workspace"
// link to (packages/marketing/src/App.tsx). --base-href=/app/ makes its asset URLs resolve
// correctly under that subpath instead of the site root. Needs env/production.json (gitignored,
// see apps/mobile/README.md) — same requirement the Codemagic iOS build already has.
const mobileDir = join(root, 'apps/mobile');
const flutterWeb = spawnSync('flutter', [
  'build', 'web',
  '-t', 'lib/main_production.dart',
  '--dart-define-from-file=env/production.json',
  '--base-href=/app/',
  // Self-host CanvasKit/skwasm instead of loading them from gstatic, so the
  // /app/ CSP in site/_worker.js can keep script-src to 'self'.
  '--no-web-resources-cdn',
], { cwd: mobileDir, stdio: 'inherit', shell: true });
if (flutterWeb.error) throw flutterWeb.error;
if (flutterWeb.status !== 0) process.exit(flutterWeb.status ?? 1);
cpSync(join(mobileDir, 'build/web'), join(output, 'app'), { recursive: true });

console.log('Built marketing site and Flutter web app in dist-site.');
